### ISSUE TITLE
It just doesn't work

### ISSUE THREAD

**Issue by spierepf** [xia0/OctoPrint-TerminalResponse#3]
I am trying to add a beep when the bed temp cools to a certain level. Here is my regex:

`Recv:  T:\d*\.\d* \/0\.00 B:3\d\.\d* \/0\.00 @:0 B@:0`

I've tested it at https://regexr.com/548oi

However, the plugin does not send the beep command to the printer:

`M300 S440 P200`

**Comment by xia0** [comment]
> 
> 
> I am trying to add a beep when the bed temp cools to a certain level. Here is my regex:
> 
> `Recv: T:\d*\.\d* \/0\.00 B:3\d\.\d* \/0\.00 @:0 B@:0`
> 
> I've tested it at https://regexr.com/548oi
> 
> However, the plugin does not send the beep command to the printer:
> 
> `M300 S440 P200`

Do not put "Recv: " in the regex. The following worked for me for responding to bed temperatures >= 30 and < 40 which is what it looks like you are trying to achieve. Please be aware though that the printer will continue to beep until it falls out of this range.

Match:
`B:(3[\d\.]*)`

Response:
`M117 bed temp (1)`

Edit: the regex will also match at 3 degrees..

**Comment by xia0** [comment]
Closing this issue due to solution provided and no response from OP.

**Comment by xia0** [comment]
To OP: This plugin is probably more suited to what you are trying to achieve.
http://plugins.octoprint.org/plugins/CooldownNotification/
