### ISSUE TITLE
Plugin not working with OctoPrint 1.5.3

### ISSUE THREAD

**Issue by MassimoVisona** [xia0/OctoPrint-TerminalResponse#4]
Hello,
I really loved this plugin. Recently I updated my OctoPrint installation to:
OctoPrint 1.5.3 Python 3.7.3 OctoPi 0.18.0

Now the plugin is not working as expected when I use the regex option. 

I want to read from terminal a string like this "// SPEED: 200.0 EXTR: 100.0" and output "M117 SPEED: 200.0% | EXTR: 100.0%".
So, before updating, using OctoPrint 1.3.8 it was working setting the plugin as:
regex: // SPEED: ([^\s]*) EXTR: ([^\s]*)
command: SPEED: (1)% | EXTR: (2)%

But now it is not working anymore, the command isn't getting executed.

Thank you very much for your help.

**Comment by xia0** [comment]
For regex, try:
`\/\/ SPEED: ([\d\.]*) EXTR: ([\d\.]*)`
and for command, try:
`M117 SPEED: (1)% | EXTR: (2)%`

**Comment by MassimoVisona** [comment]
I tried your suggestion and it isn't working. The command isn't executed at all.

In the other hand, if I use:
`regex: // SPEED: [^\s] EXTR: [^\s]`
`command: SPEED: (1)% | EXTR: (2)%`
the command is executed but it writes "SPEED: (1)% | EXTR: (2)%" and not the values I wanted.

Same thing if I use "\/\/ SPEED: [\d\.]* EXTR: [\d\.]*"

**Comment by xia0** [comment]
You need the brackets in regex because they're capture tokens.
Try `// SPEED: ([^\s]*) EXTR: ([^\s]*)`

**Comment by MassimoVisona** [comment]
Thank you again but it still doesn't work... The command isn't executed.
The fun fact is that it was working with the previous version of OctoPrint that I was using (v1.3.8).

**Comment by xia0** [comment]
Yeah thats weird. Im on the version you are and it's working for me. Can you test it with a different regular expression and see if any other capture tokens work?

**Comment by MassimoVisona** [comment]
I found the problem: in the log I was getting a lot of `AttributeError: module 'string' has no attribute 'replace'`
I then changed the `string.replace` in the `__init__.py` to the Python3 alternative `str.replace`.

**Comment by xia0** [comment]
Thanks for picking that up. I'll have to update my python version and fix it.

**Comment by MassimoVisona** [comment]
Thank you for your work! I'm glad I helped just a little bit!

**Comment by xia0** [comment]
Fixed in 0.1.3.
