### ISSUE TITLE
Can't see plugin

### ISSUE THREAD

**Issue by MarloSM** [xia0/OctoPrint-TerminalResponse#5]
Hi there, I can't find where I can configure the plugin anywhere. Am I missing something?

![image](https://user-images.githubusercontent.com/22463469/116812065-c7321f80-aba0-11eb-98a4-fa450821a98e.png)

![image](https://user-images.githubusercontent.com/22463469/116812081-ddd87680-aba0-11eb-8bd6-bb4aba7fd2aa.png)

**Comment by xia0** [comment]
Hmm that's really strange. I haven't checked the plugin with OctoPrint 1.6 yet. Is that what you're currently running?

**Comment by MarloSM** [comment]
Yes, 1.6.0.

**Comment by xia0** [comment]
Alright I just updated it and I am getting the same behaviour as you. I'll take a look this afternoon.

**Comment by xia0** [comment]
It seems that installing the plugin does not actually put it into the plugins directory (mine is ~/OctoPrint/venv3/lib/python3.7/site-packages).

**Comment by MarloSM** [comment]
I can see that I have the following folders in ~OctoPrint/venv/Lib/site-packages/. Is that what I should be seeing?

![image](https://user-images.githubusercontent.com/22463469/116829746-b6fa5e80-abf9-11eb-95c9-93fbc3888794.png)

![image](https://user-images.githubusercontent.com/22463469/116829758-c8436b00-abf9-11eb-8fa6-c2f75f0d810f.png)

**Comment by jneilliii** [comment]
The above PR should resolve this issue, replacing the deprecated control property with the current method of plugin loading. @MarloSM if you wanted you could manually install the version by copying/pasting the URL below into Plugin Manager > Get More > ...from URL and clicking Install, otherwise you'll need to wait for @xia0 to merge and publish a new release version.

```
https://github.com/jneilliii/OctoPrint-TerminalResponse/archive/refs/heads/master.zip
```

**Comment by MarloSM** [comment]
It works, thanks for the help!
